package model;

/**
 * Created by suqiaoe on 2019/4/9.
 */
public enum InterfaceName {
    //微信端接口
    AUTHORITY,CASELIST,GETINSUREDADNINSURANCE,CASESAVE,CASEINFO,CASEDELETE,
    IMAGELIST,IMAGEUPLOAD,IMAGEDELETE,IMAGEOCR,
    //保健康接口
    BJKREPORT,INDIVIDUALININSURANCE,BJKPUSHPIC
}
